UPDATE public.products SET active = false;

INSERT INTO public.products (name, description, price, image_url, images, category, stock, active, discount_percent, sort_order, badge)
VALUES
('7 Chakra Tree','Bring harmony, positive energy, and spiritual balance into your home or workspace with this handcrafted 7 Chakra Crystal Tree. Made with natural crystals representing all seven chakras, this beautiful crystal tree is believed to attract positive vibrations, encourage emotional well-being, and create a peaceful environment.',860,'product-1.jpg',ARRAY['product-1.jpg'],'Crystals',50,true,0,1,'Bestseller'),
('Ranga Dhatu Sarp Set','The Ranga Dhatu Sarp Set consists of 11 pairs (22 serpents) crafted from lead (Ranga Dhatu). Traditionally recommended in specific Vedic remedies, this set is commonly used during Kaal Sarp Dosh Nivaran rituals and other prescribed astrological pujas. This product should be used only after consultation with an experienced astrologer.',1950,'product-2.jpg',ARRAY['product-2.jpg'],'Remedies',30,true,0,2,NULL),
('Moonstone Bracelet','The Moonstone Bracelet is crafted from genuine natural Moonstone beads, admired for their soft, luminous appearance and calming energy. In Vedic astrology, the Moon governs the mind, emotions, intuition, and mental peace. A balanced Moon is believed to support emotional stability, clarity of thought, and harmonious relationships.

Traditionally known as the Mother of All Planets, Moonstone is associated with nurturing energy, compassion, and emotional well-being. It is often recommended for individuals who experience stress, confusion, mood swings, or excessive overthinking.',750,'product-3.jpg',ARRAY['product-3.jpg'],'Bracelets',60,true,0,3,NULL),
('Rose Quartz Bracelet','The Rose Quartz Bracelet is crafted from natural Rose Quartz gemstones, traditionally known as the Stone of Love. It is believed to attract love, strengthen relationships, encourage self-love, and promote emotional healing. Whether you are looking to nurture an existing relationship or searching for a thoughtful gift for someone special, this bracelet symbolizes affection, compassion, and harmony.',600,'product-4.jpg',ARRAY['product-4.jpg'],'Bracelets',60,true,0,4,NULL),
('Pyrite Bracelet','The Pyrite Bracelet is crafted from natural Pyrite gemstones, traditionally associated with Shani (Saturn) in Vedic astrology. Often known as the Stone of Prosperity, Pyrite is believed to attract wealth, enhance confidence, remove financial obstacles, and support individuals facing struggles in their personal or professional life. Traditionally, this bracelet is recommended to be worn on the left hand after consultation with a qualified astrologer.',750,'product-5.jpg',ARRAY['product-5.jpg'],'Bracelets',60,true,0,5,NULL),
('Sunstone Bracelet','The Sunstone Bracelet is crafted from natural Sunstone gemstones, traditionally associated with confidence, leadership, and success. It is believed to inspire motivation, attract opportunities, and support long-term growth, making it a popular choice for business owners, entrepreneurs, managers, and professionals seeking progress in their careers and ventures.',750,'product-6.jpg',ARRAY['product-6.jpg'],'Bracelets',60,true,0,6,NULL),
('Carnelian Bracelet','The Carnelian Bracelet is crafted from natural Carnelian gemstones, traditionally associated with Mangal (Mars) in Vedic astrology. Known as the Stone of Courage and Action, Carnelian is believed to enhance confidence, increase motivation, balance the Sacral Chakra, and channel Mars powerful energy in a positive and productive way.',750,'product-7.jpg',ARRAY['product-7.jpg'],'Bracelets',60,true,0,7,NULL),
('Tiger Eye Bracelet','The Tiger Eye Bracelet is crafted from natural Tiger Eye gemstones, traditionally known as the Stone of Courage and Confidence. It is believed to boost self-confidence, improve focus, enhance decision-making, and provide protection from negative energies. Perfect for professionals, entrepreneurs, students, and anyone striving to achieve their goals with confidence.',750,'product-8.jpg',ARRAY['product-8.jpg'],'Bracelets',60,true,0,8,NULL),
('7 Chakra Black Tourmaline Bracelet','The 7 Chakra Black Tourmaline Bracelet combines the protective properties of Black Tourmaline with the healing energy of the Seven Chakra gemstones. Traditionally believed to protect against negative energy, Nazar Dosh (evil eye), and emotional stress, this bracelet also helps balance the body seven chakras. Suitable for anyone aged 10 years and above.',650,'product-9.jpg',ARRAY['product-9.jpg'],'Bracelets',60,true,0,9,NULL),
('Dhanyog Bracelet','The Dhanyog Bracelet is a premium combination of carefully selected natural crystals traditionally believed to attract wealth, prosperity, confidence, success, and positive energy. Designed for everyday wear, this bracelet is suitable for both men and women and is ideal for entrepreneurs, professionals, students, and anyone looking to invite abundance into their life.',750,'product-10.jpg',ARRAY['product-10.jpg'],'Bracelets',60,true,0,10,'Premium');